export enum PaymentMethod {
    CASH_PAYMENT = 'CASH_PAYMENT',
    CARD_PAYMENT = 'CARD_PAYMENT',
    PAYPAL_PAYMENT = 'PAYPAL_PAYMENT',
    STRIPE_PAYMENT = 'STRIPE_PAYMENT',
    CRYPTO_PAYMENT = 'CRYPTO_PAYMENT',
}